apiVersion: v1
kind: Service
metadata:
  name: lesson-service
spec:
  selector:
    app: lesson-service
  type: NodePort
  ports:
    - name: http
      port: 8100
      nodePort: 31000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson-service
spec:
  selector:
    matchLabels:
      app: lesson-service
  replicas: 1
  template:
    metadata:
      labels:
        app: lesson-service
    spec:
      containers:
        - name: server
          image: 17501750/lesson-service
          ports:
            - name: http
              containerPort: 8100

---